import type {
  Automation,
  AutomationLog,
  Client,
  Connector,
  Deployment,
  FollowUp,
  Lead,
  LeadReport,
  MessageIntake,
  Project,
  Repository,
  WordPressSite,
} from "./types";

const now = new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
const daysAhead = (n: number) => new Date(Date.now() + n * 86400000).toISOString();

export const demoClients: Client[] = [
  {
    id: "cli_gould",
    name: "Gould Barbers",
    contact_person: "Operations Manager",
    website: "gouldbarbers.co.uk",
    country: "UK",
    location: "Northampton",
    status: "prospect",
  },
  {
    id: "cli_nexify",
    name: "Nexify Studio",
    contact_person: "Interné",
    website: "nexifystudio.com",
    country: "SK",
    status: "active",
  },
];

export const demoLeads: Lead[] = [
  {
    id: "lead_gould",
    company_name: "Gould Barbers",
    website: "gouldbarbers.co.uk",
    country: "UK",
    location: "Northampton, 60+ pobočiek",
    company_size: "500+",
    category: "Multi-location barbers",
    score_total: 92,
    score_max: 100,
    score_label: "KEEP",
    status: "new",
    problem_evidence: "Web bez online rezervačného systému, iba telefón. Slabá mobilná verzia.",
    trigger_event: "Otvorenie 3 nových pobočiek za posledný kvartál.",
    revenue_impact: "£8k–£15k / mesiac dodatočný revenue z online booking.",
    email: "info@gouldbarbers.co.uk",
    phone: "+44 1604 000000",
    contact_url: "https://gouldbarbers.co.uk/contact",
    decision_makers: [
      {
        name: "John Gould",
        role: "Founder",
        linkedin_url: "https://linkedin.com/in/example-gould",
      },
    ],
    sources: [
      {
        source_text: "Companies House filing 2025",
        source_url: "https://find-and-update.company-information.service.gov.uk",
      },
      { source_text: "Google Maps – 63 pobočiek" },
    ],
    drafts: [
      {
        id: "d_gould_1",
        lead_id: "lead_gould",
        channel: "email",
        subject: "Online booking pre Gould Barbers",
        body: "Dobrý deň John,\n\nvšimol som si, že Gould Barbers otvoril tri nové pobočky, ale rezervácie stále bežia iba cez telefón. Vieme dodať mobile-first booking do 3 týždňov.\n\n— Marek, Nexify Studio",
        follow_up_day: 3,
        follow_up_message: "Krátky follow-up: máte 15 min tento týždeň?",
        is_sent: false,
        created_at: now,
      },
    ],
    warnings: ["ESTIMATED_REVENUE_IMPACT"],
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
  },
  {
    id: "lead_dinez",
    company_name: "Dinez Taxis",
    website: "dineztaxis.co.uk",
    country: "UK",
    location: "Leicester",
    company_size: "50–200",
    category: "Premium taxi",
    score_total: 84,
    score_max: 100,
    score_label: "KEEP",
    status: "approved",
    problem_evidence: "Bez PWA, bez push notifikácií, iba webová stránka.",
    trigger_event: "Rebranding v Q2 2026.",
    revenue_impact: "PWA + booking flow: odhad +12 % konverzia.",
    email: "bookings@dineztaxis.co.uk",
    decision_makers: [{ name: "Sam Patel", role: "Managing Director" }],
    sources: [{ source_text: "LinkedIn company page" }],
    drafts: [],
    warnings: ["NO_PUBLIC_EMAIL"],
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: "lead_cutabove",
    company_name: "Cut Above Studios",
    website: "cutabovestudios.com",
    country: "US",
    location: "Austin, TX",
    company_size: "10–50",
    category: "Creative agency",
    score_total: 71,
    score_max: 100,
    score_label: "BORDERLINE",
    status: "contacted",
    problem_evidence: "Zastaraný WordPress, pomalé LCP (>4s).",
    trigger_event: "Nový CMO nastúpil.",
    revenue_impact: "Redizajn + Core Web Vitals fix.",
    email: "hello@cutabovestudios.com",
    decision_makers: [{ name: "Elena Rivera", role: "CMO" }],
    sources: [{ source_text: "PageSpeed Insights audit" }],
    drafts: [],
    warnings: ["CONTACT_FORM_ONLY"],
    created_at: daysAgo(3),
    updated_at: daysAgo(2),
  },
  {
    id: "lead_poppys",
    company_name: "Poppy's Funerals",
    website: "poppysfunerals.co.uk",
    country: "UK",
    location: "London",
    company_size: "50–200",
    category: "Local services",
    score_total: 58,
    score_max: 100,
    score_label: "BORDERLINE",
    status: "follow_up_due",
    problem_evidence: "Chýbajúca online dokumentácia pre pozostalých.",
    trigger_event: "Expanzia do Brightonu.",
    revenue_impact: "Client portal – strednodobý dopad.",
    decision_makers: [{ name: "Poppy Mardall", role: "Founder" }],
    sources: [{ source_text: "Interview v Guardian, 2025" }],
    drafts: [],
    warnings: ["UNVERIFIED_DECISION_MAKER"],
    created_at: daysAgo(5),
    updated_at: daysAgo(4),
  },
  {
    id: "lead_petvet",
    company_name: "The Pet Vet",
    website: "thepetvet.co.uk",
    country: "UK",
    location: "Yorkshire",
    company_size: "200+",
    category: "Clinics",
    score_total: 88,
    score_max: 100,
    score_label: "KEEP",
    status: "replied",
    problem_evidence: "Rezervácie roztrieštené medzi pobočkami.",
    trigger_event: "Akvizícia dvoch kliník.",
    revenue_impact: "Unified booking systém – vysoký dopad.",
    email: "practice@thepetvet.co.uk",
    decision_makers: [{ name: "Dr. Sarah Cliffe", role: "Practice Director" }],
    sources: [{ source_text: "Interná databáza kliník" }],
    drafts: [],
    warnings: [],
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
  },
];

export const demoReports: LeadReport[] = [
  {
    id: "rep_003",
    report_number: "003",
    report_date: daysAgo(0).slice(0, 10),
    title: "DAILY LEAD REPORT 003",
    average_keep_score: 88,
    keep_count: 3,
    rejected_count: 1,
    conclusion: "Silný deň – 3 KEEP leady, dominuje UK multi-location segment.",
    raw_text: "DAILY LEAD REPORT 003 — (demo)",
    created_at: now,
  },
];

export const demoFollowUps: FollowUp[] = [
  {
    id: "fu_1",
    lead_id: "lead_poppys",
    due_date: daysAhead(0),
    status: "pending",
    notes: "Zavolať / poslať draft email.",
  },
  {
    id: "fu_2",
    lead_id: "lead_gould",
    due_date: daysAhead(2),
    status: "pending",
  },
];

export const demoProjects: Project[] = [
  {
    id: "prj_nexify_crm",
    name: "Nexify CRM Clean V1",
    description: "Interný CRM systém pre Nexify Studio.",
    status: "active",
    stack: ["React", "TypeScript", "Supabase"],
    repo_url: "https://github.com/nexify/nexify-crm",
    deployment_url: "https://crm.nexifystudio.com",
    priority: "high",
    created_at: daysAgo(30),
    updated_at: daysAgo(1),
  },
  {
    id: "prj_cmr_flutter",
    name: "CMR Plus Central Dashboard (Flutter)",
    description: "Mobilná verzia centrálneho dashboardu.",
    status: "planned",
    stack: ["Flutter", "Dart", "Supabase"],
    priority: "medium",
    created_at: daysAgo(20),
    updated_at: daysAgo(3),
  },
  {
    id: "prj_pdf",
    name: "AAA PDF Convertor",
    description: "PDF statement generator pre klientov.",
    status: "shipped",
    stack: ["Node.js", "pdf-lib"],
    repo_url: "https://github.com/nexify/aaa-pdf",
    priority: "low",
    created_at: daysAgo(90),
    updated_at: daysAgo(10),
  },
  {
    id: "prj_aifix",
    name: "WorkGardSleepCode / AI FIX",
    description: "AI asistent pre code review a bug fix návrhy.",
    status: "active",
    stack: ["TypeScript", "OpenAI"],
    priority: "high",
    created_at: daysAgo(15),
    updated_at: daysAgo(0),
  },
  {
    id: "prj_studio_web",
    name: "Nexify Studio Website",
    description: "Verejný web + case studies.",
    status: "maintenance",
    stack: ["Next.js", "Tailwind"],
    deployment_url: "https://nexifystudio.com",
    priority: "medium",
    created_at: daysAgo(180),
    updated_at: daysAgo(20),
  },
  {
    id: "prj_base44",
    name: "Base44 Daily Lead Agent",
    description: "Denný agent pre lead scouting a scoring.",
    status: "active",
    stack: ["Node.js", "OpenAI", "n8n"],
    priority: "high",
    created_at: daysAgo(45),
    updated_at: daysAgo(0),
  },
  {
    id: "prj_wp_sites",
    name: "WordPress Client Sites",
    description: "Údržba a monitoring klientských WP inštalácií.",
    status: "maintenance",
    stack: ["WordPress", "PHP"],
    priority: "medium",
    created_at: daysAgo(365),
    updated_at: daysAgo(2),
  },
];

export const demoRepos: Repository[] = [
  {
    id: "repo_1",
    name: "nexify/nexify-crm",
    provider: "github",
    repo_url: "https://github.com/nexify/nexify-crm",
    default_branch: "main",
    last_commit: "feat(leads): score badge on card",
    open_issues: 4,
    open_prs: 2,
    status: "mock",
    project_id: "prj_nexify_crm",
  },
  {
    id: "repo_2",
    name: "nexify/aaa-pdf",
    provider: "github",
    repo_url: "https://github.com/nexify/aaa-pdf",
    default_branch: "main",
    last_commit: "chore: bump pdf-lib",
    open_issues: 0,
    open_prs: 0,
    status: "mock",
    project_id: "prj_pdf",
  },
  {
    id: "repo_3",
    name: "nexify/ai-fix",
    provider: "github",
    repo_url: "https://github.com/nexify/ai-fix",
    default_branch: "develop",
    last_commit: "fix(worker): rate limit handling",
    open_issues: 7,
    open_prs: 3,
    status: "mock",
    project_id: "prj_aifix",
  },
];

export const demoDeployments: Deployment[] = [
  {
    id: "dep_1",
    project_id: "prj_nexify_crm",
    provider: "vercel",
    deployment_url: "https://nexify-crm-git-main.vercel.app",
    production_url: "https://crm.nexifystudio.com",
    status: "ready",
    branch: "main",
    commit_hash: "a1b2c3d",
    created_at: daysAgo(0),
  },
  {
    id: "dep_2",
    project_id: "prj_studio_web",
    provider: "vercel",
    deployment_url: "https://nexify-studio.vercel.app",
    production_url: "https://nexifystudio.com",
    status: "ready",
    branch: "main",
    commit_hash: "f4e5d6a",
    created_at: daysAgo(2),
  },
  {
    id: "dep_3",
    project_id: "prj_aifix",
    provider: "vercel",
    deployment_url: "https://ai-fix-preview.vercel.app",
    status: "error",
    branch: "develop",
    commit_hash: "9b8c7d6",
    created_at: daysAgo(1),
  },
];

export const demoWordPress: WordPressSite[] = [
  {
    id: "wp_1",
    name: "Client – Local Clinic",
    site_url: "https://clinic-example.com",
    admin_url: "https://clinic-example.com/wp-admin",
    status: "healthy",
    wp_version: "6.6.2",
    plugins_count: 14,
    theme: "Astra Child",
    notes: "Denné zálohy cez UpdraftPlus.",
  },
  {
    id: "wp_2",
    name: "Client – Barbers UK",
    site_url: "https://barbers-example.co.uk",
    admin_url: "https://barbers-example.co.uk/wp-admin",
    status: "warning",
    wp_version: "6.5.4",
    plugins_count: 22,
    theme: "Custom",
    notes: "PHP 8.0 – naplánovať upgrade na 8.2.",
  },
];

export const demoMessages: MessageIntake[] = [
  {
    id: "msg_1",
    source: "imessage",
    raw_text:
      "Ahoj, videl som vašu prácu pre Cut Above. Sme malé fitness štúdio v Bratislave, hľadáme booking systém. Rozpočet ~2500 €. Volaj +421 900 123 456.",
    parsed_company: "Fitness Bratislava",
    parsed_contact: "Neznámy",
    parsed_phone: "+421 900 123 456",
    parsed_budget: "~2500 €",
    parsed_service: "Booking systém",
    status: "new",
    created_at: daysAgo(0),
  },
];

export const demoAutomations: Automation[] = [
  {
    id: "auto_base44",
    name: "Base44 Lead Import Webhook",
    description: "Prijíma denný lead report cez webhook.",
    status: "mock",
    icon: "Inbox",
  },
  {
    id: "auto_github",
    name: "GitHub Sync",
    description: "Synchronizuje repozitáre a PR každú hodinu.",
    status: "mock",
    icon: "Github",
  },
  {
    id: "auto_vercel",
    name: "Vercel Deployment Sync",
    description: "Sťahuje stav deploymentov z Vercel API.",
    status: "mock",
    icon: "Rocket",
  },
  {
    id: "auto_wp",
    name: "WordPress Health Check",
    description: "Kontroluje uptime a WP verziu klientských sitov.",
    status: "mock",
    icon: "Globe",
  },
  {
    id: "auto_followup",
    name: "Follow-up Reminder",
    description: "Denná pripomienka follow-upov v CRM.",
    status: "enabled",
    icon: "Bell",
    last_run: daysAgo(0),
  },
  {
    id: "auto_msg",
    name: "Message-to-Lead Parser",
    description: "Konvertuje pasted správy na CRM lead drafty.",
    status: "enabled",
    icon: "MessageSquare",
    last_run: daysAgo(0),
  },
];

export const demoLogs: AutomationLog[] = [
  {
    id: "log_1",
    source: "Base44",
    action: "import.report",
    status: "success",
    message: "DAILY LEAD REPORT 003 importovaný (5 leadov, 3 KEEP).",
    created_at: daysAgo(0),
  },
  {
    id: "log_2",
    source: "Vercel",
    action: "deploy.error",
    status: "error",
    message: "Build failed: ai-fix (develop) – TypeScript error.",
    created_at: daysAgo(1),
  },
  {
    id: "log_3",
    source: "WordPress",
    action: "health.check",
    status: "warning",
    message: "barbers-example.co.uk beží na PHP 8.0.",
    created_at: daysAgo(1),
  },
  {
    id: "log_4",
    source: "Follow-up",
    action: "reminder",
    status: "info",
    message: "1 follow-up má termín dnes.",
    created_at: daysAgo(0),
  },
];

export const demoConnectors: Connector[] = [
  {
    id: "c_github",
    name: "GitHub",
    provider: "github",
    status: "missing",
    config_summary: "Server-side token, read-only scope.",
    required_env: ["GITHUB_TOKEN"],
  },
  {
    id: "c_vercel",
    name: "Vercel",
    provider: "vercel",
    status: "missing",
    config_summary: "Deployments + projects API.",
    required_env: ["VERCEL_TOKEN"],
  },
  {
    id: "c_base44",
    name: "Base44",
    provider: "base44",
    status: "mock",
    config_summary: "Webhook pre denný lead report.",
    required_env: ["BASE44_WEBHOOK_SECRET"],
  },
  {
    id: "c_wp",
    name: "WordPress",
    provider: "wordpress",
    status: "missing",
    config_summary: "Application password per site.",
    required_env: ["WORDPRESS_SITE_URL", "WORDPRESS_USERNAME", "WORDPRESS_APP_PASSWORD"],
  },
  {
    id: "c_twilio",
    name: "Twilio SMS",
    provider: "twilio",
    status: "missing",
    config_summary: "SMS drafty len – žiadne auto-odosielanie.",
    required_env: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_FROM_NUMBER"],
  },
  {
    id: "c_crm",
    name: "CRM Auth",
    provider: "internal",
    status: "missing",
    config_summary: "Interný token pre webhooky.",
    required_env: ["CRM_AUTH_TOKEN"],
  },
];
