/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordpressRouteImport } from './routes/wordpress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsImportRouteImport } from './routes/leads.import'
import { Route as ApiPublicHooksBase44RouteImport } from './routes/api/public/hooks/base44'

const WordpressRoute = WordpressRouteImport.update({
  id: '/wordpress',
  path: '/wordpress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsImportRoute = LeadsImportRouteImport.update({
  id: '/leads/import',
  path: '/leads/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBase44Route = ApiPublicHooksBase44RouteImport.update({
  id: '/api/public/hooks/base44',
  path: '/api/public/hooks/base44',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/logs': typeof LogsRoute
  '/messages': typeof MessagesRoute
  '/projects': typeof ProjectsRoute
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/wordpress': typeof WordpressRoute
  '/leads/import': typeof LeadsImportRoute
  '/api/public/hooks/base44': typeof ApiPublicHooksBase44Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/logs': typeof LogsRoute
  '/messages': typeof MessagesRoute
  '/projects': typeof ProjectsRoute
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/wordpress': typeof WordpressRoute
  '/leads/import': typeof LeadsImportRoute
  '/api/public/hooks/base44': typeof ApiPublicHooksBase44Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/logs': typeof LogsRoute
  '/messages': typeof MessagesRoute
  '/projects': typeof ProjectsRoute
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/wordpress': typeof WordpressRoute
  '/leads/import': typeof LeadsImportRoute
  '/api/public/hooks/base44': typeof ApiPublicHooksBase44Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automations'
    | '/crm'
    | '/dashboard'
    | '/deployments'
    | '/logs'
    | '/messages'
    | '/projects'
    | '/repos'
    | '/settings'
    | '/wordpress'
    | '/leads/import'
    | '/api/public/hooks/base44'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automations'
    | '/crm'
    | '/dashboard'
    | '/deployments'
    | '/logs'
    | '/messages'
    | '/projects'
    | '/repos'
    | '/settings'
    | '/wordpress'
    | '/leads/import'
    | '/api/public/hooks/base44'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/automations'
    | '/crm'
    | '/dashboard'
    | '/deployments'
    | '/logs'
    | '/messages'
    | '/projects'
    | '/repos'
    | '/settings'
    | '/wordpress'
    | '/leads/import'
    | '/api/public/hooks/base44'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AutomationsRoute: typeof AutomationsRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  DeploymentsRoute: typeof DeploymentsRoute
  LogsRoute: typeof LogsRoute
  MessagesRoute: typeof MessagesRoute
  ProjectsRoute: typeof ProjectsRoute
  ReposRoute: typeof ReposRoute
  SettingsRoute: typeof SettingsRoute
  WordpressRoute: typeof WordpressRoute
  LeadsImportRoute: typeof LeadsImportRoute
  ApiPublicHooksBase44Route: typeof ApiPublicHooksBase44Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordpress': {
      id: '/wordpress'
      path: '/wordpress'
      fullPath: '/wordpress'
      preLoaderRoute: typeof WordpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/import': {
      id: '/leads/import'
      path: '/leads/import'
      fullPath: '/leads/import'
      preLoaderRoute: typeof LeadsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/base44': {
      id: '/api/public/hooks/base44'
      path: '/api/public/hooks/base44'
      fullPath: '/api/public/hooks/base44'
      preLoaderRoute: typeof ApiPublicHooksBase44RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AutomationsRoute: AutomationsRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  DeploymentsRoute: DeploymentsRoute,
  LogsRoute: LogsRoute,
  MessagesRoute: MessagesRoute,
  ProjectsRoute: ProjectsRoute,
  ReposRoute: ReposRoute,
  SettingsRoute: SettingsRoute,
  WordpressRoute: WordpressRoute,
  LeadsImportRoute: LeadsImportRoute,
  ApiPublicHooksBase44Route: ApiPublicHooksBase44Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
